- project/activities/models.py
> Use Person.companions model property

- project/people/templates/people/companion_confirm_delete.html
- project/people/templates/people/person_applicant.html
- project/people/templates/people/person_companion.html
- project/people/templates/people/person_detail.html
- project/people/urls.py
- project/people/views.py
Closes #28 
Changes
- ability to remove companion from person
- separate template into components
> [feat] remove companions

- project/templates/navigation.html
> Remove "Caregivers" menu item

- project/accounts/forms.py
- project/accounts/urls.py
- project/accounts/views.py
> Profile code cleanup

- project/accounts/templates/registration/login.html
- project/accounts/templates/registration/signup.html
- project/accounts/views.py
> Automatically login after registration

- project/accounts/templates/accounts/profile.html
- project/accounts/urls.py
- project/accounts/views.py
Hello Geri,
I have come up with class based update profile view in your "accounts" app - kindly have a look.
Thanks,
A
> Accounts - class based user profile update view

- project/accounts/forms.py
- project/accounts/models.py
- project/activities/admin.py
- project/activities/apps.py
- project/activities/forms.py
- project/activities/views.py
- project/caregivers/models.py
- project/core/asgi.py
- project/core/settings.py
- project/core/urls.py
- project/core/wsgi.py
- project/locale/fi/LC_MESSAGES/django.po
- project/manage.py
- project/people/apps.py
- project/people/templates/people/companion_confirm_delete.html
- project/people/templates/people/person_activity.html
- project/people/templates/people/person_add_activity_modal.html
- project/people/templates/people/person_applicant.html
- project/people/templates/people/person_companion.html
- project/people/templates/people/person_detail.html
- project/people/templates/people/person_invite_companion_modal.html
- project/people/templates/people/person_list.html
- project/people/tests.py
- project/templates/home.html
- project/templates/i18n.html
- project/templates/navigation.html
> I18n audit

- .github/workflows/python.yml
- project/accounts/models.py
- project/accounts/tests.py
- project/accounts/views.py
- project/activities/models.py
- project/activities/tests.py
- project/caregivers/tests.py
- project/core/settings.py
- project/people/models.py
- project/people/tests.py
- project/people/views.py
- pyproject.toml
> Improve CI workflow

- project/accounts/templates/accounts/password_change.html
- project/accounts/templates/accounts/password_change_complete.html
- project/accounts/urls.py
- project/templates/navigation.html
Add password change feature.
Co-authored by: Kelvin Munyao <kelvinmunyao01@gmail.com>
> Add password change URLs, templates, and link

- project/accounts/urls.py
> Redirect to person list on login

- project/activities/urls.py
- project/activities/views.py
- project/people/templates/people/person_activity.html
- project/people/templates/people/person_detail.html
Closes #44
Changes
- reorganize activity buttons into dropdown
- add "delete activity" action with confirmation modal
- clean up code for consistency and and maintainability
- under consideration: whether to use generic modals for all activities instead of rendering three modals per activty (would require modal to support passing parameters to internal form)
> Delete scheduled activities

- project/people/templates/people/person_detail.html
- project/people/templates/people/person_list.html
> Conditional person photo

- .github/workflows/codecov.yml
- .github/workflows/python.yml
- CONTRIBUTING.md
- poetry.lock
- pyproject.toml
> Test coverage report

- CONTRIBUTING.md
Signed-off-by: Brylie Christopher Oxley <brylie@amble.fi>
> Use signing link that displays CLA text

- project/core/management/commands/makemigrations.py
Adds makemigrations.py to disable auto-named migrations as laid out in the issue
Closes https://github.com/CompanionshipCare/companionship-care/issues/105
> Adds makemigrations.py to disable auto-named migrations

- .editorconfig
- CONTRIBUTING.md
- Adds .editorConfig as detailed in the issue.
- Adds short description to CONTRIBUTING.md
Closes https://github.com/CompanionshipCare/companionship-care/issues/102
> Adds .editorConfig & updates CONTRIBUTING.md

- .github/workflows/python.yml
- project/core/management/commands/makemigrations.py
Signed-off-by: Brylie Christopher Oxley <brylie@amble.fi>
> Update python test/lint for fork support

- .pre-commit-config.yaml
> pre-commit config file add issue 92

- CONTRIBUTING.md
> 119 - Add instructions for resolving conflicts in poetry.lock

- poetry.lock
- project/core/settings.py
- pyproject.toml
> Added Rich terminal output

- project/core/settings.py
> Add LOGGING.version

- project/core/settings.py
> dictionary version error removed

- project/people/admin.py
> Register admin for remaining models

- project/people/admin.py
> Add missing JoinRequest import

- project/core/urls.py
- project/error_handling/views.py
- project/templates/400.html
- project/templates/403.html
- project/templates/404.html
- project/templates/500.html
resolves https://github.com/CompanionshipCare/companionship-care/issues/76
> added error page templates

- project/circles/templates/circles/circle_detail.html
- project/circles/views.py
- project/templates/404.html
resolves https://github.com/CompanionshipCare/companionship-care/issues/15
> pagination translation component added, and grammar fixes to 500.html

- Personae.md
This file provides four personae who might use Companionship Care. These may help in making design or build choices. These may be refined or added to as the program develops, and the use cases get clearer.
> Add Personae.md
